  default: &default
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    host: localhost
    username: <%= Rails.application.credentials.db_user_name %>
    password: <%= Rails.application.credentials.db_password %>

  development:
    <<: *default
    database: delivery_app_development

  test:
    <<: *default
    database: delivery_app_test

  production:
    <<: *default
    database: delivery_app_production
